### ISSUE TITLE
[Persistence] NullReferenceException when Persistence folder is filled

### ISSUE THREAD

**Issue by clintnetwork** [Type-DB/Core#14]
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at TypeDB.Instance.<>c__DisplayClass15_0.<OpenDatabase>b__1(Database x) in C:\Users\me\Projets\Type-DB\Core\Type-DB.Core\Instance.cs:line 84
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at TypeDB.Instance.OpenDatabase(String databaseName, Boolean createIfNotExist) in C:\Users\me\Projets\Type-DB\Core\Type-DB.Core\Instance.cs:line 84
   at DirectUSING.Program.Main(String[] args) in C:\Users\me\source\DirectUSING\Program.cs:line 19
```

**Comment by clintnetwork** [comment]
#9
